blank_issues_enabled: false
contact_links:
  - name: Documentation
    url: https://github.com/F2had/famfolio#configuration
    about: Check the documentation before opening an issue
  - name: Discussions
    url: https://github.com/F2had/famfolio/discussions
    about: Ask questions and share ideas
